version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"

  graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - GRAYLOG_PASSWORD_SECRET=S3cr3tSenhaQualquer
      - GRAYLOG_ROOT_PASSWORD_SHA2=61646d696e
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    restart: always


